name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.os }}

    env:
      Project_Path: SoftwareCopyrightSourceCodeCollector.Desktop/SoftwareCopyrightSourceCodeCollector.Desktop.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild on Windows
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v2

    - name: Restore .NET workloads
      run: dotnet workload restore

    - name: Publish application
      run: dotnet publish ${{ env.Project_Path }} -c ${{ matrix.configuration }} --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:PublishTrimmed=false --runtime ${{ matrix.os == 'windows-latest' && 'win-x64' || matrix.os == 'ubuntu-latest' && 'linux-x64' || 'osx-x64' }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: |
          **/bin/${{ matrix.configuration }}/net8.0/win-x64/publish/
          **/bin/${{ matrix.configuration }}/net8.0/linux-x64/publish/
          **/bin/${{ matrix.configuration }}/net8.0/osx-x64/publish/
