name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:

  build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        configuration: [Release]

    runs-on: ${{ matrix.os }}

    env:
      Project_Path: SoftwareCopyrightSourceCodeCollector.Desktop/SoftwareCopyrightSourceCodeCollector.Desktop.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish application
      run: dotnet publish ${{ env.Project_Path }} -c ${{ matrix.configuration }} --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:PublishTrimmed=false --runtime ${{ matrix.os == 'windows-latest' && 'win-x64' || matrix.os == 'ubuntu-latest' && 'linux-x64' || 'osx-x64' }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build-${{ matrix.configuration }}-${{ github.run_id }}
        path: |
          **/bin/${{ matrix.configuration }}/net8.0/win-x64/publish/
          **/bin/${{ matrix.configuration }}/net8.0/linux-x64/publish/
          **/bin/${{ matrix.configuration }}/net8.0/osx-x64/publish/

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: github.event_name == 'release'
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: '**/bin/Release/net8.0/*/publish/*'
        asset_name: release-${{ matrix.os }}.zip
        asset_content_type: application/zip
